awsAccount: "526919081086"
awsRegion: us-west-1

network:
  vpc:
    cidr: 10.151.96.0/21
  tgw:
    name: TGW
    description: "This is TGW"
    id: tgw-0744dec08946ededc
data:
  elasticsearch:
    capacity:
      masterNodes:
        instanceType: t2.small.elasticsearch
        count: 3
      dataNodes:
        instanceType: t2.small.elasticsearch
        count: 3
    ebs:
      volumeSize: 10
    zoneAwareness:
      enabled: true
      count: 3
    logging:
      appLogEnabled: false
      auditLogEnabled: false
      slowIndexLogEnabled: false
      slowIearchLogEnabled: false
